<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Mdq.Core\Mdq.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <Version>0.0.1</Version>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <Target Name="InjectVersionConstants" BeforeTargets="CoreCompile">
    <ItemGroup>
        <Compile Include="$(IntermediateOutputPath)VersionConstants.g.cs" />
    </ItemGroup>
    <WriteLinesToFile File="$(IntermediateOutputPath)VersionConstants.g.cs" Overwrite="True" Lines="
namespace Mdq.Cli%3B
public static class AppVersion {
    public const string Number = &quot;$(Version)&quot;%3B
}" />
  </Target>

</Project>
